require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  Exclude:
    - 'examples/**/*'
    - 'spec/samples/**/*'

# Commands may have long output lines
Layout/LineLength:
  Exclude:
    - 'lib/kojo/commands/*.rb'

# Allow longer examples
RSpec/ExampleLength:
  Max: 24

# Allow `expect` instead of `allow` in some cases
RSpec/StubbedMock:
  Exclude:
    - 'spec/kojo/form_spec.rb'
    - 'spec/tty_spec_helper.rb'
